---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_NAME'] || 'chef-testing' %>
  region: <%= ENV['AWS_REGION'] || 'us-east-1' %>
  availability_zone: <%= ENV['AWS_REGION'] || 'us-east-1' %>a
  require_chef_omnibus: true
  subnet_id: <%= ENV['AWS_SUBNET_ID'] %>
  security_group_ids: <%= ENV['AWS_SECURITY_GROUP_ID'] %>
  instance_type: t3.small
  associate_public_ip: true
  interface: dns
  tags:
    Project: 'chef-cookbook-testing'
    Cookbook: 'enterprise-time'
    CreatedBy: 'test-kitchen'

provisioner:
  name: chef_zero
  product_name: chef
  install_strategy: always
  chef_license: accept-silent

verifier:
  name: inspec

platforms:
  - name: ubuntu-20.04
    driver:
      image_id: ami-0fb0b230890ccd1e6  # Ubuntu 20.04 LTS us-east-1
      transport:
        username: ubuntu
        ssh_key: <%= ENV['AWS_SSH_KEY_PATH'] || '~/.ssh/chef-testing.pem' %>
  
  - name: centos-8
    driver:
      image_id: ami-0b17d05c24d03b9c8  # CentOS 8 us-east-1
      transport:
        username: centos
        ssh_key: <%= ENV['AWS_SSH_KEY_PATH'] || '~/.ssh/chef-testing.pem' %>
  
  - name: amazon-linux-2
    driver:
      image_id: ami-0601422bf6afa8ac3  # Amazon Linux 2 us-east-1 (latest)
      transport:
        username: ec2-user
        ssh_key: <%= ENV['AWS_SSH_KEY_PATH'] || '~/.ssh/chef-testing.pem' %>
        
  - name: windows-2019
    driver:
      image_id: ami-0c2d3e23b7708db96  # Windows Server 2019 us-east-1
      transport:
        name: winrm
        username: administrator
        password: <%= ENV['AWS_WINDOWS_PASSWORD'] %>

suites:
  - name: default
    run_list:
      - recipe[enterprise-time::default]
    attributes:
      time:
        timezone: "America/Los_Angeles"
        ntp_servers:
          - "0.pool.ntp.org"
          - "1.pool.ntp.org"
          - "2.pool.ntp.org"
  
  - name: enterprise
    run_list:
      - recipe[enterprise-time::default]
    includes:
      - ubuntu-20.04
      - centos-8
      - amazon-linux-2
    attributes:
      time:
        timezone: "UTC"
        ntp_servers:
          - "ntp1.example.com"  # Replace with your corporate NTP
          - "ntp2.example.com"
          - "0.pool.ntp.org"    # Fallback
  
  - name: windows-test
    run_list:
      - recipe[enterprise-time::default]
    includes:
      - windows-2019
    attributes:
      time:
        timezone: "Pacific Standard Time"
        ntp_servers:
          - "time.windows.com"
          - "time.nist.gov"
          - "pool.ntp.org"
  
  - name: supermarket
    run_list:
      - recipe[enterprise-time::default]
    attributes:
      time:
        timezone: "America/New_York"
        ntp_servers:
          - "0.pool.ntp.org"
          - "1.pool.ntp.org"
          - "2.pool.ntp.org"