---
driver:
  name: docker
  privileged: true
  use_sudo: false

provisioner:
  name: chef_zero
  product_name: chef
  install_strategy: always
  chef_license: accept-silent

verifier:
  name: inspec

platforms:
  - name: ubuntu-20.04
    driver_config:
      image: ubuntu:20.04
      platform: ubuntu
      run_command: /bin/systemd
      provision_command:
        - apt-get update
        - apt-get install -y sudo curl wget systemd systemd-sysv
        - systemctl set-default multi-user.target
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      tmpfs:
        - /run
        - /tmp
  
  - name: centos-8
    driver_config:
      image: quay.io/centos/centos:stream8
      platform: rhel
      run_command: /usr/sbin/init
      provision_command:
        - yum install -y sudo curl wget systemd
        - systemctl enable systemd-timesyncd || true
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro

suites:
  - name: default
    run_list:
      - recipe[time-cookbook::default]
    attributes:
      time:
        timezone: "America/New_York"
        ntp_servers:
          - "0.pool.ntp.org"
          - "1.pool.ntp.org"
          - "2.pool.ntp.org"
  
  - name: chrony
    run_list:
      - recipe[time-cookbook::default]
    includes:
      - ubuntu-20.04
      - centos-8
    attributes:
      time:
        timezone: "Europe/London"
        linux:
          use_chrony: true
          prefer_ntpd: false
        ntp_servers:
          - "0.europe.pool.ntp.org"
          - "1.europe.pool.ntp.org"