---
driver:
  name: ec2
  region: us-east-1
  instance_type: t3.small
  associate_public_ip: true
  interface: dns

provisioner:
  name: chef_infra
  install_strategy: always
  policyfile: Policyfile.rb
  chef_license: accept-silent

verifier:
  name: inspec

platforms:
  # Latest Windows Server 2022 (October 2025)
  - name: windows-2022
    driver:
      image_id: ami-043cc489b5239c3de  # Windows Server 2022 Base 2025.10.15
      instance_type: t3.medium
    transport:
      name: winrm
      username: administrator
      elevated: true

suites:
  - name: default
    run_list:
      - recipe[enterprise-time::default]
    attributes:
      time:
        timezone: Eastern Standard Time
        ntp_servers:
          - 0.pool.ntp.org
          - 1.pool.ntp.org
          - 2.pool.ntp.org
          - 3.pool.ntp.org