---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_NAME'] || 'chef-testing' %>
  region: <%= ENV['AWS_REGION'] || 'us-west-2' %>
  availability_zone: <%= ENV['AWS_REGION'] || 'us-west-2' %>a
  require_chef_omnibus: true
  subnet_id: <%= ENV['AWS_SUBNET_ID'] %>
  security_group_ids: <%= ENV['AWS_SECURITY_GROUP_ID'] %>
  instance_type: t3.small
  associate_public_ip: true
  interface: dns
  tags:
    Project: 'chef-cookbook-testing'
    Cookbook: 'time-cookbook'
    CreatedBy: 'test-kitchen'

provisioner:
  name: chef_zero
  product_name: chef
  install_strategy: always
  chef_license: accept-silent

verifier:
  name: inspec

platforms:
  - name: ubuntu-20.04
    driver:
      image_id: ami-0c2d3e23b7708db96  # Ubuntu 20.04 LTS us-west-2
      transport:
        username: ubuntu
        ssh_key: <%= ENV['AWS_SSH_KEY_PATH'] || '~/.ssh/id_rsa' %>
  
  - name: centos-8
    driver:
      image_id: ami-0686851c4e7b1a8e1  # CentOS 8 us-west-2
      transport:
        username: centos
        ssh_key: <%= ENV['AWS_SSH_KEY_PATH'] || '~/.ssh/id_rsa' %>
  
  - name: amazon-linux-2
    driver:
      image_id: ami-0c94855ba95b798c7  # Amazon Linux 2 us-west-2
      transport:
        username: ec2-user
        ssh_key: <%= ENV['AWS_SSH_KEY_PATH'] || '~/.ssh/id_rsa' %>
        
  - name: windows-2019
    driver:
      image_id: ami-0c2b0d3fb02824d92  # Windows Server 2019 us-west-2
      transport:
        name: winrm
        username: administrator
        password: <%= ENV['AWS_WINDOWS_PASSWORD'] %>

suites:
  - name: default
    run_list:
      - recipe[time-cookbook::default]
    attributes:
      time:
        timezone: "America/Los_Angeles"
        ntp_servers:
          - "0.pool.ntp.org"
          - "1.pool.ntp.org"
          - "2.pool.ntp.org"
  
  - name: enterprise
    run_list:
      - recipe[time-cookbook::default]
    includes:
      - ubuntu-20.04
      - centos-8
      - amazon-linux-2
    attributes:
      time:
        timezone: "UTC"
        ntp_servers:
          - "ntp1.example.com"  # Replace with your corporate NTP
          - "ntp2.example.com"
          - "0.pool.ntp.org"    # Fallback
  
  - name: windows-test
    run_list:
      - recipe[time-cookbook::default]
    includes:
      - windows-2019
    attributes:
      time:
        timezone: "Pacific Standard Time"
        ntp_servers:
          - "time.windows.com"
          - "time.nist.gov"
          - "pool.ntp.org"