---
driver:
  name: ec2
  aws_ssh_key_id: chef-testing
  region: us-east-1
  availability_zone: us-east-1a
  require_chef_omnibus: true
  instance_type: t3.small
  associate_public_ip: true
  interface: dns
  tags:
    Project: 'chef-cookbook-testing'
    Cookbook: 'enterprise-time'
    CreatedBy: 'test-kitchen'

provisioner:
  name: chef_infra
  install_strategy: always
  policyfile: Policyfile.rb
  chef_license: accept-silent

verifier:
  name: inspec

platforms:
  # Modern Linux Platforms
  - name: ubuntu-22.04
    driver:
      image_id: ami-0c02fb55956c7d316  # Ubuntu 22.04 LTS us-east-1
    transport:
      name: ssh
      username: ubuntu
      ssh_key: <%= ENV['AWS_SSH_KEY_PATH'] || '~/.ssh/chef-testing.pem' %>
  
  - name: amazon-linux-2023
    driver:
      image_id: ami-0a3c3a20c09d6f377  # Amazon Linux 2023 us-east-1
    transport:
      name: ssh  
      username: ec2-user
      ssh_key: <%= ENV['AWS_SSH_KEY_PATH'] || '~/.ssh/chef-testing.pem' %>

  # Modern Windows Platforms  
  - name: windows-2022
    driver:
      image_id: ami-043cc489b5239c3de  # Windows Server 2022 Base 2025.10.15 (latest)
      instance_type: t3.medium
    transport:
      name: winrm
      username: administrator
      elevated: true

  - name: windows-2019
    driver:
      image_id: ami-0c2d3e23b7708db96  # Windows Server 2019 us-east-1
      instance_type: t3.medium
    transport:
      name: winrm
      username: administrator
      elevated: true

suites:
  - name: default
    run_list:
      - recipe[enterprise-time::default]
    attributes:
      time:
        timezone: "America/New_York"
        ntp_servers:
          - "0.pool.ntp.org"
          - "1.pool.ntp.org"
          - "2.pool.ntp.org"
          - "3.pool.ntp.org"
  
  - name: enterprise-linux
    run_list:
      - recipe[enterprise-time::default]
    includes:
      - ubuntu-22.04
      - amazon-linux-2023
    attributes:
      time:
        timezone: "America/New_York"  # EST/EDT
        ntp_servers:
          - "0.pool.ntp.org"
          - "1.pool.ntp.org"
  
  - name: enterprise-windows
    run_list:
      - recipe[enterprise-time::default]
    includes:
      - windows-2022
      - windows-2019
    attributes:
      time:
        timezone: "Eastern Standard Time"
        ntp_servers:
          - "0.pool.ntp.org"
          - "1.pool.ntp.org"
          - "2.pool.ntp.org"
          - "3.pool.ntp.org"