---
driver:
  name: azurerm
  subscription_id: <%= ENV['AZURE_SUBSCRIPTION_ID'] %>
  location: 'East US'
  machine_size: 'Standard_B1s'
  vm_tags:
    project: 'chef-cookbook-testing'
    cookbook: 'time-cookbook'
    created_by: 'test-kitchen'

provisioner:
  name: chef_zero
  product_name: chef
  install_strategy: always
  chef_license: accept-silent

verifier:
  name: inspec

platforms:
  - name: ubuntu-20.04
    driver:
      image_urn: Canonical:0001-com-ubuntu-server-focal:20_04-lts-gen2:latest
      vm_name: kitchen-time-ubuntu-<%= ENV['USER'] || 'test' %>
      username: azureuser
      ssh_key: ~/.ssh/id_rsa.pub
  
  - name: centos-8
    driver:
      image_urn: OpenLogic:CentOS:8_5-gen2:latest
      vm_name: kitchen-time-centos-<%= ENV['USER'] || 'test' %>
      username: azureuser
      ssh_key: ~/.ssh/id_rsa.pub
      
  - name: windows-2019
    driver:
      image_urn: MicrosoftWindowsServer:WindowsServer:2019-Datacenter:latest
      vm_name: kitchen-time-win-<%= ENV['USER'] || 'test' %>
      username: azureuser
      password: <%= ENV['AZURE_VM_PASSWORD'] || 'ChefTest123!' %>
      winrm_transport: ssl

suites:
  - name: default
    run_list:
      - recipe[time-cookbook::default]
    attributes:
      time:
        timezone: "UTC"
        ntp_servers:
          - "0.pool.ntp.org"
          - "1.pool.ntp.org"
          - "2.pool.ntp.org"
  
  - name: custom-timezone
    run_list:
      - recipe[time-cookbook::default]
    includes:
      - ubuntu-20.04
      - windows-2019
    attributes:
      time:
        timezone: "America/New_York"
        ntp_servers:
          - "0.north-america.pool.ntp.org"
          - "1.north-america.pool.ntp.org"
  
  - name: chrony-test
    run_list:
      - recipe[time-cookbook::default]
    includes:
      - ubuntu-20.04
      - centos-8
    attributes:
      time:
        timezone: "Europe/London"
        linux:
          use_chrony: true
          prefer_ntpd: false
        ntp_servers:
          - "0.europe.pool.ntp.org"
          - "1.europe.pool.ntp.org"