name 'time-cookbook'
maintainer 'Your Name'
maintainer_email 'your.email@example.com'
license 'Apache-2.0'
description 'Installs/Configures NTP and timezone settings for Windows and Linux'
version '1.0.0'
chef_version '>= 16.0'

supports 'windows'
supports 'ubuntu'
supports 'debian'
supports 'redhat'
supports 'centos'
supports 'fedora'
supports 'amazon'
supports 'suse'

source_url 'https://github.com/bassslap/time-cookbook'
issues_url 'https://github.com/bassslap/time-cookbook/issues'
