Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/ubuntu-20.04"
  c.vm.hostname = "default-ubuntu-2004.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/Users/bphillip/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-time-cookbook-default-ubuntu-2004-e7eccb89-aae2-4ec8-8620-42c60b7185d1"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
